dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install: pip install tox-travis
script:  tox
cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv
after_success:
  - bash <(curl -s https://codecov.io/bash)