dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install: pip install tox-travis
script:  tox
addons:
  apt:
    packages:
      - libenchant-dev
cache:
  directories:
    - $HOME/.cache/pypoetry/cache
after_success:
  - bash <(curl -s https://codecov.io/bash)