[tool.poetry]
name = "pyborg"
version = "1.4.0"
description = "a chatbot suite for modern services"
authors = ["Jack Laxson <jackjrabbit@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
arrow = "^0.14.2"
PyTumblr = "^0.0.8"
requests = "^2.22"
bottle = "^0.12.17"
venusian = "^1.2"
click = "^7.0"
humanize = "^0.5.1"
praw = "^6.3"
"Mastodon.py" = "^1.4"
tweepy = "^3.7"
lxml = "^4.3"
attrs = "^19.1"
statsd = "^3.3"
prompt_toolkit = "^2.0"
"discord.py" = "^1.2"
aeidon = "^1.2"

[tool.poetry.dev-dependencies]
green = "^2.16"
coverage = "^4.5"
mock = "^3.0"
sphinx-click = "^2.2"
click = "^7.0"
sphinx-autobuild = "^0.7.1"
funcsigs = "^1.0"
mypy = "^0.711.0"
flake8 = "^3.7"
invoke = "^1.2"
fabric2 = "^2.4"
asynctest = "^0.13.0"
ipython = "^7.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 140
